# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b89e66088a28a0d2f14b715985b628a91605b08c45cf169ffe1c62924e0db68db897498feee977dbed224fb5be3b01e015f7891bbcbcf78dda3832cf81209885

test:
  secret_key_base: dc94a80f4699477b10423ee0b7b0fc90cdb020afe762ee075f32bc8bf107642b100dcef18ebd5c90330343d4b84d518bc29255179a7699a23aa907f3ab2fce4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
